name: Deployment
on:
  push:
    branches:
      - master
      - development
jobs:
  docs:
    name: Documentation deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Install Node v16
        uses: actions/setup-node@master
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Deploy documentation
        uses: discordjs/action-docs@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
